[data.handling]
# value must be an int
CHUNKSIZES = 5000
# values that are "None" will
# be ignored for the analysis
[obs.keys]
# The following are the most
# common since cell obs columns
# obs can be added or removed as needed
CELL_IDS = "None"
CELL_TYPE = "None"
SAMPLE = "None"
BATCH = "None"
N_GENES = "None"
N_COUNTS = "None"
PERCENT_MIDO = "None"
LEIDEN = "None"
CONDITION = "None"
[var.keys]
# The following are the most
# common since cell var columns
# var can be added or removed as needed
GENE_IDS = "None"
GENE_SYMBOLS = "None"
HIGHLY_VARIABLE = "None"
MEANS = "None"
DISPERSIONS = "None"
MITO = "None"
CHROMOSOME = "None"