[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]
include = ["scLint*"]

[project]
name = "scLint"
version = "0.0.1"
authors = [
  { name = "Steve Cheney", email = "scheney.cb@gmail.com" },
  { name = "Tanvir Saini", email = "tanvirxsaini@gmail.com" }
]
description = "A linter tool for validating Scanpy AnnData objects"
readme = "README.md"
requires-python = ">=3.11.11"
license = { text = "Apache-2.0" }
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: OS Independent"
]

dependencies = [

    "numpy==2.2.5",
    "pandas==2.2.3",
    "ipykernel==6.29.5",
    "matplotlib==3.10.3",
    "matplotlib-inline==0.1.7",
    "scipy==1.15.2",
    "scanpy==1.11.3",
    "seaborn==0.13.2",
    "scikit-learn==1.7.0",
    "anndata",
    "hdf5plugin",
    "zarr>=2.18.7,<3.0.0"
]

[project.optional-dependencies]
dev = [
  "pytest",
  "black",
  "black[jupyter]",
  "codespell"
]

[project.urls]
Homepage = "https://github.com/Open-Access-Comp-Bio/scLint"
Issues = "https://github.com/Open-Access-Comp-Bio/scLint/issues"

[project.scripts]
scLint = "scLint.main:main"
