name: Run Pytest on Pull Request

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          activate-environment: sclint
          auto-activate-base: false

      - name: Run tests
        shell: bash -l {0}
        run: |
          pytest